### ISSUE TITLE
[REJECTED] Not working with Protonmail

### ISSUE THREAD

**Issue by sergeevabc** [M-Gregoire/Firefox-AddUrlToWindowsTitle#2]
URL is added to the tab’s title as expected when user comes to https://mail.protonmail.com/login
But in a second URL vanishes, so the titles becomes simply “Login | ProtonMail”.
Could you fix that, please?

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by sergeevabc** [comment]
Meanwhile switched to [TitleURL][1] as it works as expected.

[1]: https://addons.mozilla.org/en-US/firefox/addon/url-in-title/

**Comment by M-Gregoire** [comment]
Thank you for your report. I'll take a look.

**Comment by M-Gregoire** [comment]
Hello @sergeevabc ,
ProtonMail uses [ngScp](https://docs.angularjs.org/api/ng/directive/ngCsp) to block unsafe evaluations. The content of my addons is blocked based on this rule as shown in the JS console:
```
Content Security Policy: The page's settings blocked the loading of a resource at inline ("script-src").
```.

I don't believe this is something I could fix easily.
